function ShowSituation(info, i,window)
figure
     subplot(2,2,1)
    gscatter(info{i,1}.data.z,info{i,1}.data.y,info{i,1}.data.q,'br','xo')
    axis([-window, window, -window, window])
    title(info{i,1}.param.time/1e-15)
    xlabel('z (m)')
    ylabel('y (m)')
    subplot(2,2,2)
    gscatter(info{i,1}.data.x,info{i,1}.data.z,info{i,1}.data.q,'br','xo')
    axis([-window, window, -window, window])
    title(info{i,1}.param.time/1e-15)
    xlabel('x (m)')
    ylabel('z (m)')
    subplot(2,2,3)
    gscatter(info{i,1}.data.x,info{i,1}.data.y,info{i,1}.data.q,'br','xo')
    axis([-window, window, -window, window])
    title(info{i,1}.param.time/1e-15)
    xlabel('x (m)')
    ylabel('y (m)')
    subplot(2,2,4)
    scatter3(info{i,1}.data.z,info{i,1}.data.y,info{i,1}.data.x, ((info{i,1}.data.q/1.602e-19)+1.1)*5+10, ((info{i,1}.data.q/1.602e-19)+3), 'filled')
    axis([-window, window, -window, window, -window, window])
    title(info{i,1}.param.time/1e-15)
    xlabel('z (m)')
    ylabel('y (m)')
    zlabel('x (m)')
