function showAnimate(info, time)
 close all
 subplot(2,2,1)
 t=zeros(numel(info),1);
 for i=1:numel(info)
     t(i) = info{i,1}.param.time;
 end
 [~,i] = min(abs(t-time));
     subplot(2,2,1)
    gscatter(info{i,1}.data.z,info{i,1}.data.y,info{i,1}.data.q,'br','xo')
    axis([-2e-7, 2e-7, -2e-7, 2e-7])
    title(info{i,1}.param.time/1e-15)
    xlabel('z (m)')
    ylabel('y (m)')
    subplot(2,2,2)
    gscatter(info{i,1}.data.x,info{i,1}.data.z,info{i,1}.data.q,'br','xo')
    axis([-2e-7, 2e-7, -2e-7, 2e-7])
    title(info{i,1}.param.time/1e-15)
    xlabel('x (m)')
    ylabel('z (m)')
    subplot(2,2,3)
    gscatter(info{i,1}.data.x,info{i,1}.data.y,info{i,1}.data.q,'br','xo')
    axis([-2e-7, 2e-7, -2e-7, 2e-7])
    title(info{i,1}.param.time/1e-15)
    xlabel('x (m)')
    ylabel('y (m)')
    subplot(2,2,4)
    scatter3(info{i,1}.data.z,info{i,1}.data.y,info{i,1}.data.x, ((info{i,1}.data.q/1.602e-19)+1.1)*5+10, ((info{i,1}.data.q/1.602e-19)+3), 'filled')
    axis([-2e-7, 2e-7, -2e-7, 2e-7, -2e-7, 2e-7])
    title(info{i,1}.param.time/1e-15)
    xlabel('z (m)')
    ylabel('y (m)')
    zlabel('x (m)')
    pause(0.001)
